obj-$(CONFIG_CRYPTO_DEV_HISI_HACV1) += hisi_hacv1.o
hisi_hacv1-objs = hisi_sec_algs.o hisi_sec_drv_v1.o

obj-$(CONFIG_CRYPTO_DEV_HISI_HAC_TEST) += crypt_hac_test.o
crypt_hac_test-objs := hisi_hac_test.o
